/******************************************************************************

@File         XEPropertyObjectSocket.h

@Version       1.0

@Created      2018, 1, 15

@Description  The class ids of each class in X Editor

@HISTORY:

******************************************************************************/
#ifndef _XEPROPERTYOBJECTESOCKET_H
#define _XEPROPERTYOBJECTESOCKET_H
#include "XEPropertyObjectBase.h"

//modify running instances and its unique template.
class XEPropertyObjectSocket 
	:public XEPropertyObjectBase
{
public:
	XEPropertyObjectSocket(){};
	~XEPropertyObjectSocket(){};
	enum{ 
		PROPERTY_TRANSFORM_NODE = XEPropertyTree::USER_PROPRETY_INDEX, PROPERTY_LOCATION,PROPERTY_ROTATION, PROPERTY_SCALE,
		PROPERTY_PREVIEWING_NODE, PROPERTY_PREVIEWING_ASSET_PATH, PROPERTY_PREVIEWING_REMOVE,PROPERTY_PREVIEWING_PARTICLE_RESTART,
		PROPERTY_PREVIEWING_ANIMATION_NODE, PROPERTY_ANIMATION_AUTO_PLAY,PROPERTY_ANIMATION_LOOP,PROPERTY_ANIMATION_PREVIEW,PROPERTY_ANIMATION_PATH,
		PROPERTY_BIND_OBJECT_BEGIN, PROPERTY_BIND_OBJECT_END = 500,
		PROPERTY_PREVIEWING_PHYSICS_NODE,
		PROPERTY_PREVIEWING_PHYSICS_PATH,
		PROPERTY_PREVIEWING_PHYSICS_REMOVE,
		PROPERTY_PREVIEWING_PHYSICS_RIGID_TYPE,
		PROPERTY_PREVIEWING_PHYSICS_RIGID_GRAVITY,
		PROPERTY_PREVIEWING_PHYSICS_LINER_DAMPING,
		PROPERTY_PREVIEWING_PHYSICS_ANGULAR_DAMPING,
		PROPERTY_PREVIEWING_PHYSICS_RIGID_MASS,
		PROPERTY_PREVIEWING_PHYSICS_RIGID_UCC,
		PROPERTY_PREVIEWING_PHYSICS_RIGID_LINEAR_SPEED,
		PROPERTY_PREVIEWING_PHYSICS_RIGID_ANGULAR_SPEED,
		PROPERTY_PREVIEWING_PHYSICS_MATERIAL_STATIC_FRICTION,
		PROPERTY_PREVIEWING_PHYSICS_MATERIAL_DYNAMIC_FRICTION,
		PROPERTY_PREVIEWING_PHYSICS_MATERIAL_RESTITUTION,
		PROPERTY_PREVIEWING_PHYSICS_MATERIA_NAME
	};
public:
	virtual xbool	GetPropertyTree(xint32 nFilter, XEPropertyTree &PropTree) override;
	virtual	xbool	SetPropertyValue(const XEProperty &Node, xbool bNotifyPropertyChanged = xtrue) override;
	virtual	xbool	GetPropertyValue(XEProperty &Node) override;

private:
	xbool			HasAnimationList(const XString& strFolderPath);
};

#endif // _XEPROPERTYOBJECTESOCKET_H
