/******************************************************************************

@File         XEPropertyObjectMaterialCurveParameter.h

@Version       1.0

@Created      2018, 9, 27

@Description  The class ids of each class in X Editor

@HISTORY:

******************************************************************************/
#ifndef _XEPROPERTYOBJECT_MATFX_DISTRIBUTION_PARAMETER_H_
#define _XEPROPERTYOBJECT_MATFX_DISTRIBUTION_PARAMETER_H_
#include "XEPropertyObjectBase.h"

//modify running instances and its unique template.
class XEPropertyObjectMatFxDistributionParameter 
	:public XEPropertyObjectBase
{
public:
	XEPropertyObjectMatFxDistributionParameter(){};
	~XEPropertyObjectMatFxDistributionParameter(){};
	enum{ 
		PROPERTY_MATFX_ENABLE = XEPropertyTree::USER_PROPRETY_INDEX,
		PROPERTY_MATFX_DELAY_TIME,
		PROPERTY_MATFX_DURATION_TIME,

		PROPERTY_MATFX_POINT_DISTRIBUTION_ROOT,
		PROPERTY_MATFX_POINT_DISTRIBUTION_GROUP,
		PROPERTY_MATFX_POINT_DISTRIBUTION_TYPE,

		//NONE-CURVE
		PROPERTY_MATFX_POINT_CONSTANT,
		PROPERTY_MATFX_POINT_UNIFORM_MAX,
		PROPERTY_MATFX_POINT_UNIFORM_MIN,

		//CURVE
		PROPERTY_MATFX_CURVE_POINTS,
		PROPERTY_MATFX_CURVE_POINTS_ADD_REMOVE,

		PROPERTY_MATFX_CURVE_POINT_INDEX_START,
		PROPERTY_MATFX_CURVE_POINT_INVAL_START,
		PROPERTY_MATFX_CURVE_POINT_OUTVAL_START,
		PROPERTY_MATFX_CURVE_POINT_OUTVAL1_START,
		PROPERTY_MATFX_CURVE_POINT_OUTVAL2_START,
		PROPERTY_MATFX_CURVE_POINT_ARRIVETANGENT_START,
		PROPERTY_MATFX_CURVE_POINT_ARRIVETANGENT1_START,
		PROPERTY_MATFX_CURVE_POINT_ARRIVETANGENT2_START,
		PROPERTY_MATFX_CURVE_POINT_LEAVETANGENT_START,
		PROPERTY_MATFX_CURVE_POINT_LEAVETANGENT1_START,
		PROPERTY_MATFX_CURVE_POINT_LEAVETANGENT2_START,
		PROPERTY_MATFX_CURVE_POINT_INTERPMODE_START,

		PROPERTY_MATFX_CURVE_POINT_INDEX_END = PROPERTY_MATFX_CURVE_POINT_INDEX_START + 1024,
		PROPERTY_MATFX_CURVE_POINT_INVAL_END,
		PROPERTY_MATFX_CURVE_POINT_OUTVAL_END,
		PROPERTY_MATFX_CURVE_POINT_OUTVAL1_END,
		PROPERTY_MATFX_CURVE_POINT_OUTVAL2_END,
		PROPERTY_MATFX_CURVE_POINT_ARRIVETANGENT_END,
		PROPERTY_MATFX_CURVE_POINT_ARRIVETANGENT1_END,
		PROPERTY_MATFX_CURVE_POINT_ARRIVETANGENT2_END,
		PROPERTY_MATFX_CURVE_POINT_LEAVETANGENT_END,
		PROPERTY_MATFX_CURVE_POINT_LEAVETANGENT1_END,
		PROPERTY_MATFX_CURVE_POINT_LEAVETANGENT2_END,
		PROPERTY_MATFX_CURVE_POINT_INTERPMODE_END,

		PROPERTY_MATFX_CURVE_BREATHING,
		PROPERTY_MATFX_CURVE_LOOP,
		PROPERTY_MATFX_CURVE_LOOP_KEY_OFFSET,

		PROPERTY_MATFX_LOCK_AXES1,
		PROPERTY_MATFX_LOCK_AXES2
	};
public:
	virtual xbool	GetPropertyTree(xint32 nFilter, XEPropertyTree &PropTree) override;
	virtual	xbool	SetPropertyValue(const XEProperty &Node, xbool bNotifyPropertyChanged = xtrue) override;
	virtual	xbool	GetPropertyValue(XEProperty &Node) override;
protected:
	static XArray<XString>& GetCurvePointDistributionGroup();
	static XArray<XString>& GetCurvePointInterpMode();
	static XArray<XString>& GetCurveLockAxesType();
};

#endif // _XEPROPERTYOBJECT_MATFX_DISTRIBUTION_PARAMETER_H_
